### ISSUE TITLE
AWS RDS Aurora Serverless v2

### ISSUE THREAD

**Issue by jensenbox** [spa5k/uids-postgres#5]
Is there any support for installing on Aurora? I read some documentation mentioning they support TLE but I am unable to determine any overlap with pgrx.

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/PostgreSQL_trusted_language_extension.html

Any guidance on this is welcome.

Thanks!

**Comment by spa5k** [comment]
Pretty sure that isn't possible since they don't really give you this level of access to the internal db. You can try either doing UUID_V7 or Typeid to get some custom sortable IDs.


https://aws.amazon.com/blogs/database/implement-uuidv7-in-amazon-rds-for-postgresql-using-trusted-language-extensions/

https://github.com/jetify-com/typeid

Both of them will likely work directly as they are in pure SQL, or in aws supported format.
